### ISSUE TITLE
Serial driver

### ISSUE THREAD

**Issue by longevity-software** [VolksEEG/eeg-device-firmware#4]
#Summary
Serial port driver to sit before the protocol frame parser and call the appropriate lower level Serial library. 

#Requirements 
- [x] Buffer receiver data, so it can be requested by other modules.
- [x] Buffer data to transmit, and control emptying of this buffer.

**Comment by alcohen** [comment]
So something like a circular buffer each for sending and receiving? 

A module can request samples, say the last N samples or the samples since sample #Y?

A module can also set the driver to empty at a certain rate, then start adding to the buffer? Actually, is rate important since the receiver can infer time by each sample packet's ordinality?

**Comment by alcohen** [comment]
(It feels a bit naughty to do this without OOP, but I don't see that it really matters too much.)

But... d'oh!... Arduino can work with c++ code so it can be oop. I think.

**Comment by longevity-software** [comment]
> So something like a circular buffer each for sending and receiving?

Yeah, all this really provides on top of the Arduino Serial class, is the buffering of data so it can be processed asynchronously.

**Comment by longevity-software** [comment]
This work is completed in the current GrahamDevlop branch at this point in time https://github.com/VolksEEG/eeg-device-firmware/tree/4159de6c7182921b9b42821d15b9887fab20376d.
